{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ee2c6003",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting boto\n",
      "  Downloading boto-2.49.0-py2.py3-none-any.whl (1.4 MB)\n",
      "                                              0.0/1.4 MB ? eta -:--:--\n",
      "     -------                                  0.2/1.4 MB 5.0 MB/s eta 0:00:01\n",
      "     ------------------------                 0.8/1.4 MB 10.5 MB/s eta 0:00:01\n",
      "     ---------------------------------------  1.4/1.4 MB 10.7 MB/s eta 0:00:01\n",
      "     ---------------------------------------- 1.4/1.4 MB 7.8 MB/s eta 0:00:00\n",
      "Installing collected packages: boto\n",
      "Successfully installed boto-2.49.0\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install boto"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9b945c4a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#console sign in link\n",
    "#https://680050888106.signin.aws.amazon.com/console"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "b8b8e655",
   "metadata": {},
   "outputs": [],
   "source": [
    "import boto\n",
    "import boto.s3.connection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "7af43e72",
   "metadata": {},
   "outputs": [],
   "source": [
    "access_key='AKIAZ4VRRBWVOEMGDB3U'\n",
    "secret_key='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'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "2e0963db",
   "metadata": {},
   "outputs": [],
   "source": [
    "conn =boto.connect_s3(\n",
    "                  aws_access_key_id='AKIAZ4VRRBWVOEMGDB3U',\n",
    "                  aws_secret_access_key='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')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "0eaca6a9",
   "metadata": {},
   "outputs": [
    {
     "ename": "S3ResponseError",
     "evalue": "S3ResponseError: 403 Forbidden\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>WKTGK2T8XT5QJCN4</RequestId><HostId>aU8Xt9/bIUZf+jJYG6UBYB8U8oL0oBGGnvPAc7JUNAM57X4hHslb0qVv3wtUuj79o1jQieUa+Bo=</HostId></Error>",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mS3ResponseError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[20], line 1\u001b[0m\n\u001b[1;32m----> 1\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m bucket \u001b[38;5;129;01min\u001b[39;00m conn\u001b[38;5;241m.\u001b[39mget_all_buckets():\n\u001b[0;32m      2\u001b[0m     \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;132;01m{name}\u001b[39;00m\u001b[38;5;130;01m\\t\u001b[39;00m\u001b[38;5;132;01m{created}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(\n\u001b[0;32m      3\u001b[0m             name\u001b[38;5;241m=\u001b[39mbucket\u001b[38;5;241m.\u001b[39mname,\n\u001b[0;32m      4\u001b[0m             created\u001b[38;5;241m=\u001b[39mbucket\u001b[38;5;241m.\u001b[39mcreation_date,\n\u001b[0;32m      5\u001b[0m     ))\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\boto\\s3\\connection.py:446\u001b[0m, in \u001b[0;36mS3Connection.get_all_buckets\u001b[1;34m(self, headers)\u001b[0m\n\u001b[0;32m    444\u001b[0m body \u001b[38;5;241m=\u001b[39m response\u001b[38;5;241m.\u001b[39mread()\n\u001b[0;32m    445\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m response\u001b[38;5;241m.\u001b[39mstatus \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m300\u001b[39m:\n\u001b[1;32m--> 446\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprovider\u001b[38;5;241m.\u001b[39mstorage_response_error(\n\u001b[0;32m    447\u001b[0m         response\u001b[38;5;241m.\u001b[39mstatus, response\u001b[38;5;241m.\u001b[39mreason, body)\n\u001b[0;32m    448\u001b[0m rs \u001b[38;5;241m=\u001b[39m ResultSet([(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mBucket\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbucket_class)])\n\u001b[0;32m    449\u001b[0m h \u001b[38;5;241m=\u001b[39m handler\u001b[38;5;241m.\u001b[39mXmlHandler(rs, \u001b[38;5;28mself\u001b[39m)\n",
      "\u001b[1;31mS3ResponseError\u001b[0m: S3ResponseError: 403 Forbidden\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>WKTGK2T8XT5QJCN4</RequestId><HostId>aU8Xt9/bIUZf+jJYG6UBYB8U8oL0oBGGnvPAc7JUNAM57X4hHslb0qVv3wtUuj79o1jQieUa+Bo=</HostId></Error>"
     ]
    }
   ],
   "source": [
    "# for bucket in conn.get_all_buckets():\n",
    "#     print(\"{name}\\t{created}\".format(\n",
    "#             name=bucket.name,\n",
    "#             created=bucket.creation_date,\n",
    "#     ))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "79fc162d",
   "metadata": {},
   "outputs": [
    {
     "ename": "S3ResponseError",
     "evalue": "S3ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>M5AFRET3ZNR1G7WF</RequestId><HostId>xLVt2DD8ho2Y6A8Vsk4pn0uk4pL2IyV+DOTumK7+VE+xNf+n3PXp8tyUSq3UuJgaBtfX9XQg6No=</HostId></Error>",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mS3ResponseError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[21], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;66;03m#creating bucket\u001b[39;00m\n\u001b[1;32m----> 2\u001b[0m bucket1\u001b[38;5;241m=\u001b[39mconn\u001b[38;5;241m.\u001b[39mcreate_bucket(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mbuck1\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[1;32m~\\anaconda3\\Lib\\site-packages\\boto\\s3\\connection.py:627\u001b[0m, in \u001b[0;36mS3Connection.create_bucket\u001b[1;34m(self, bucket_name, headers, location, policy)\u001b[0m\n\u001b[0;32m    625\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mbucket_class(\u001b[38;5;28mself\u001b[39m, bucket_name)\n\u001b[0;32m    626\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 627\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mprovider\u001b[38;5;241m.\u001b[39mstorage_response_error(\n\u001b[0;32m    628\u001b[0m         response\u001b[38;5;241m.\u001b[39mstatus, response\u001b[38;5;241m.\u001b[39mreason, body)\n",
      "\u001b[1;31mS3ResponseError\u001b[0m: S3ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>M5AFRET3ZNR1G7WF</RequestId><HostId>xLVt2DD8ho2Y6A8Vsk4pn0uk4pL2IyV+DOTumK7+VE+xNf+n3PXp8tyUSq3UuJgaBtfX9XQg6No=</HostId></Error>"
     ]
    }
   ],
   "source": [
    "#creating bucket\n",
    "bucket1=conn.create_bucket('buck1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77ae9414",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
